FROM oven/bun:1
WORKDIR /app
ARG DATABASE_URL
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./package* .
COPY ./apps/web ./web

RUN bun install
RUN bun run db:generate
ENV DATABASE_URL=${secrets.DATABASE_URL}||"postgresql://postgres:mysecretpassword@localhost:5432/postgres"
RUN bun run build
EXPOSE 3000
CMD [ "bun",'run','start:web' ]