name: CI CD BACKEND
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Pushing to Docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: rajulthakur/todo-app: ${{github.sha}}
